### ISSUE TITLE
Error with Angular and DataGrid

### ISSUE THREAD

**Issue by jtsom** [DevExpress/DevExtreme.AspNet.Data#186]
I'm trying to use the DevExtreme DataGrid, along with an MVC Core 2 backend and the AspNet.Data library. However, the data is not displayed and there is an error in the console.

My MVC Core backend already works fine with the DevExtreme MVC controls.

I'm using the CI version of the AspNet.Data package, so as to not require JQuery. These are the packages from the Angular app:

```
    "devextreme": "^17.2.5",
    "devextreme-angular": "^17.2.5",
    "devextreme-aspnet-data-nojquery": "https://ci.appveyor.com/api/buildjobs/4jdis8ted8so9hm2/artifacts/devextreme-aspnet-data-nojquery-99.0.0-ci-000404.tgz",

```

The code in the Angular component, is pretty bare-bones:

app.component.ts:
```
import { Component, OnInit } from '@angular/core';
import * as AspNetData from 'devextreme-aspnet-data-nojquery';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent implements OnInit {
  dataSource: any;
  url: string;

  constructor() {
    this.url = 'https://localhost:44378/Home/GetPlans';
  }

  ngOnInit() {
    this.dataSource = AspNetData.createStore({
      key: 'PlanId',
      loadUrl: this.url,
      loadParams: {contactId: 'F9F6CB4F-7ECB-4529-A19F-C5AD455BEBB0'}
    });
  }

}
```

app.component.html:
```
<dx-data-grid
  [dataSource]="dataSource"
  [remoteOperations]="true"
  height="600"
  [showBorders]="true"

  >
  <dxi-column dataField="PlanId"></dxi-column>
  <dxi-column dataField="PlanName"></dxi-column>
  <dxi-column dataField="State"></dxi-column>
  <dxi-column dataField="City"></dxi-column>
</dx-data-grid>
```

The MVC controller code gets called and returns the data just fine. Here is the call:

```
        public IActionResult GetPlans(DataSourceLoadOptions loadOptions, string contactId)
        {
            var plans = _service.GetPlansForContact(contactId);   // returns List<> of data
            var loadResults = DataSourceLoader.Load(plans, loadOptions);
            return Ok(loadResults);
        }
```

I am implementing the DataSourceLoadOptions class per the docs.

What I see in the console is:

![image](https://user-images.githubusercontent.com/13488/35624271-87d04b88-065c-11e8-80b6-41fd264616c0.png)

The Network tab in the Chrome Debugger shows the data is returned, in what looks like the correct format:

![image](https://user-images.githubusercontent.com/13488/35624332-b27de5c0-065c-11e8-8d60-3c665c51816c.png)

![image](https://user-images.githubusercontent.com/13488/35624472-105fd89c-065d-11e8-983d-dc2952796da4.png)

Please let me know if I can provide more info.

**Comment by AlekseyMartynov** [comment]
Thanks.
Caused by https://github.com/DevExpress/DevExtreme/issues/2770.

**Comment by jtsom** [comment]
To reproduce the error in https://github.com/DevExpress/DevExtreme/issues/2770 just create a new angular application and add the devextreme packages noted. Start the app and try to load the page (http://localhost:4200). You shouldn't need to set up a .NET server application, as it never gets to the point of making the network request.

**Comment by jtsom** [comment]
Well, slight update.

I updated the devextreme-aspnet-data-nojquery package to the latest ci version (https://ci.appveyor.com/api/buildjobs/1pnc430saq607ddg/artifacts/devextreme-aspnet-data-nojquery-99.0.0-ci-000413.tgz) and that stack error seems to be gone. (thought there is still a dependency issue: `npm WARN devextreme-angular@17.2.5 requires a peer of devextreme@~17.2.5 but none was installed.`

It gets as far as making the request, now I just have to deal with a CORS issue, but that's on my side.

Thanks.

**Comment by AlekseyMartynov** [comment]
Hello @jtsom 
We have published a release candidate of [devextreme-aspnet-data-nojquery](https://www.npmjs.com/package/devextreme-aspnet-data-nojquery).
We would appreciate if you test this build and drop us a line in ticket #200.

**Comment by jtsom** [comment]
Noting here, and will there too - after installing the RC version, I'm now seeing:

```
core.js:1448 ERROR RangeError: Maximum call stack size exceeded
    at extend (extend.js:23)
    at Object.Deferred._promise.promise (deferred.js:84)
    at new Deferred (deferred.js:86)
    at new exports.Deferred (deferred.js:159)
    at inheritor._loadImpl (custom_store.js:221)
    at inheritor.eval [as _loadImpl] (class.js:16)
    at inheritor.load [as _loadFunc] (abstract_store.js:55)
    at invokeUserLoad (custom_store.js:71)
    at inheritor._loadImpl (custom_store.js:225)
    at inheritor.eval [as _loadImpl] (class.js:16)
```

If I comment out the <dx-data-grid> from the .html, it doesn't appear, so it looks like there's something going on.

**Comment by AlekseyMartynov** [comment]
Closing due to inactivity.

**Comment by jtsom** [comment]
Sorry to say, but the latest version of this and the devextreme and devextreme-angular packages still have an error:

webpack-internal:///./node_modules/@angular/core/esm5/core.js:1664 ERROR RangeError: Maximum call stack size exceeded
    at extend (webpack-internal:///./node_modules/devextreme/core/utils/extend.js:23)
    at Object.Deferred._promise.promise (webpack-internal:///./node_modules/devextreme/core/utils/deferred.js:84)
    at new Deferred (webpack-internal:///./node_modules/devextreme/core/utils/deferred.js:86)
    at new exports.Deferred (webpack-internal:///./node_modules/devextreme/core/utils/deferred.js:159)
    at inheritor._loadImpl (webpack-internal:///./node_modules/devextreme/data/custom_store.js:221)
    at inheritor.eval [as _loadImpl] (webpack-internal:///./node_modules/devextreme/core/class.js:16)
    at inheritor.load [as _loadFunc] (webpack-internal:///./node_modules/devextreme-aspnet-data-nojquery/node_modules/devextreme/data/abstract_store.js:55)
    at invokeUserLoad (webpack-internal:///./node_modules/devextreme/data/custom_store.js:71)
    at inheritor._loadImpl (webpack-internal:///./node_modules/devextreme/data/custom_store.js:225)
    at inheritor.eval [as _loadImpl] (webpack-internal:///./node_modules/devextreme/core/class.js:16)
